kind: pipeline
name: default

steps:
  - name: Go test
    image: golang:1.11
    environment:
      GO111MODULE: on
    commands:
      - go mod download
      - go test ./...

  - name: publish
    image: plugins/gcr
    settings:
      registry: gcr.io
      repo: exq365-stage-218912/postmaster
      tags: latest
      json_key:
        from_secret: GOOGLE_SERVICE_ACCOUNT

trigger:
  branch:
  - exq365
  event:
  - push